{"name": "test_case[case0]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/sonic/Project/Python/Pytest/logs/2020-04-09.log'", "trace": "self = <uti.RequestHandler.RequestHandler object at 0x11035e210>\n\n    def send_request(self):\n        \"\"\" 发请求 \"\"\"\n        try:\n            response = requests.request(\n                method=self.case['method'],\n>               url=basurl + self.case['url'],\n                params=self._check_params()\n            )\nE           NameError: name 'basurl' is not defined\n\nuti/RequestHandler.py:36: NameError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test_case.Test_case object at 0x110374490>, case = {'expect': 0.0, 'id': 'asc-0001', 'isRun': 'RUN', 'message': '', ...}\n\n    @pytest.mark.parametrize('case', ExcelHandler().get_excel_data)\n    def test_case(self, case):\n        \"\"\"  执行断言 \"\"\"\n        # print(case)\n        # 发请求\n>       response = RequestHandler(case).get_response\n\nscripts/test_case.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nuti/RequestHandler.py:28: in get_response\n    response = self.send_request()\nuti/RequestHandler.py:47: in send_request\n    logger().error({'response': \"请求发送失败，详细信息： url={}\".format(self.case['url'])})\nuti/LoggerHandler.py:55: in logger\n    file_level=conf.LOG_FILE_LEVEL\nuti/LoggerHandler.py:31: in __init__\n    f_file = logging.FileHandler(self.file_name)\n/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py:1087: in __init__\n    StreamHandler.__init__(self, self._open())\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <[AttributeError(\"'FileHandler' object has no attribute 'level'\") raised in repr()] FileHandler object at 0x11037b510>\n\n    def _open(self):\n        \"\"\"\n        Open the current base file with the (original) mode and encoding.\n        Return the resulting stream.\n        \"\"\"\n>       return open(self.baseFilename, self.mode, encoding=self.encoding)\nE       FileNotFoundError: [Errno 2] No such file or directory: '/Users/sonic/Project/Python/Pytest/logs/2020-04-09.log'\n\n/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py:1116: FileNotFoundError"}, "description": "  执行断言 ", "parameters": [{"name": "case", "value": "{'id': 'asc-0001', 'module': '口碑', 'url': 'baidu.com', 'isRun': 'RUN', 'method': 'GET', 'parameter': '', 'expect': 0.0, 'result': '', 'message': ''}"}], "start": 1586446302523, "stop": 1586446302523, "uuid": "1b44883f-7b26-4046-881d-8add70a079e8", "historyId": "8969fb93535c3ccbd57d0d36069d62f2", "testCaseId": "ea02412fdf50230ea9175db2c24ad2e1", "fullName": "scripts.test_case.Test_case#test_case", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "Test_case"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "8423-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_case"}]}