{"name": "test_excel[ dpquery: \"\",\n            qid : \"\",\n            cid : \"\",\n            sid : \"1468_31118_21106_31187_31228_30824_31164_31196\",\n  ]", "status": "failed", "statusDetails": {"message": "AssertionError: assert b' dpquery: \"...4_31196\",\\n  ' == '<Response [200]>'\n  +b' dpquery: \"\",\\n            qid : \"\",\\n            cid : \"\",\\n            sid : \"1468_31118_21106_31187_31228_30824_31164_31196\",\\n  '\n  -'<Response [200]>'", "trace": "data = b' dpquery: \"\",\\n            qid : \"\",\\n            cid : \"\",\\n            sid : \"1468_31118_21106_31187_31228_30824_31164_31196\",\\n  '\n\n    @pytest.mark.parametrize('data', ExcelHandler.get_excel_data(1))\n    def test_excel(data):\n>       assert data == '<Response [200]>'\nE       assert b' dpquery: \"...4_31196\",\\n  ' == '<Response [200]>'\nE         +b' dpquery: \"\",\\n            qid : \"\",\\n            cid : \"\",\\n            sid : \"1468_31118_21106_31187_31228_30824_31164_31196\",\\n  '\nE         -'<Response [200]>'\n\ntest.py:16: AssertionError"}, "parameters": [{"name": "data", "value": "<class 'bytes'>"}], "start": 1586663321744, "stop": 1586663321744, "uuid": "123a320a-8ba8-4829-8d38-a59b470d9665", "historyId": "9d955464e551031910104e1a1868cec5", "testCaseId": "1a84b5fa1cd8fc91bc1e7f314e541701", "fullName": "allure.test#test_excel", "labels": [{"name": "parentSuite", "value": "allure"}, {"name": "suite", "value": "test"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "42329-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure.test"}]}