{
  "uid" : "d6001259fa17c304",
  "name" : "test_case[case2]",
  "fullName" : "scripts.test_case.Test_case#test_case",
  "historyId" : "fac1fcb6ccb71c4ed49bb5fbd5696efb",
  "time" : {
    "start" : 1586449153310,
    "stop" : 1586449153310,
    "duration" : 0
  },
  "description" : "  执行断言 ",
  "descriptionHtml" : "<p>执行断言</p>\n",
  "status" : "broken",
  "statusMessage" : "KeyError: 'case_project'",
  "statusTrace" : "self = <scripts.test_case.Test_case object at 0x10b0160d0>\ncase = {'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'id': 'asc-0003', 'isRun': 'RUN', 'message': '', ...}\n\n    @pytest.mark.parametrize('case', ExcelHandler().get_excel_data)\n    def test_case(self, case):\n        \"\"\"  执行断言 \"\"\"\n        # print(case)\n        # 发请求\n        response = RequestHandler(case).get_response\n    \n        # 制作 allure 报告\n>       allure.dynamic.title(case['case_project'])\nE       KeyError: 'case_project'\n\nscripts/test_case.py:29: KeyError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_Class__pytest_setup_class",
    "time" : {
      "start" : 1586449153189,
      "stop" : 1586449153189,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "  执行断言 ",
    "status" : "broken",
    "statusMessage" : "KeyError: 'case_project'",
    "statusTrace" : "self = <scripts.test_case.Test_case object at 0x10b0160d0>\ncase = {'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'id': 'asc-0003', 'isRun': 'RUN', 'message': '', ...}\n\n    @pytest.mark.parametrize('case', ExcelHandler().get_excel_data)\n    def test_case(self, case):\n        \"\"\"  执行断言 \"\"\"\n        # print(case)\n        # 发请求\n        response = RequestHandler(case).get_response\n    \n        # 制作 allure 报告\n>       allure.dynamic.title(case['case_project'])\nE       KeyError: 'case_project'\n\nscripts/test_case.py:29: KeyError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "befe8588f1487daa",
      "name" : "log",
      "source" : "befe8588f1487daa.txt",
      "type" : "text/plain",
      "size" : 159
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "_Class__pytest_setup_class::0",
    "time" : {
      "start" : 1586449153327,
      "stop" : 1586449170169,
      "duration" : 16842
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "scripts"
  }, {
    "name" : "suite",
    "value" : "test_case"
  }, {
    "name" : "subSuite",
    "value" : "Test_case"
  }, {
    "name" : "host",
    "value" : "localhost"
  }, {
    "name" : "thread",
    "value" : "10306-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "scripts.test_case"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "{'id': 'asc-0003', 'module': 'flask', 'url': 'http://127.0.0.1:8888/login?name=yuhang&pw=999', 'isRun': 'RUN', 'method': 'GET', 'parameter': '', 'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'result': '', 'message': ''}"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "f07d523f1b038990",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '/Users/sonic/Project/Python/Pytest/logs/2020-04-09.log'",
      "time" : {
        "start" : 1586446922210,
        "stop" : 1586446922210,
        "duration" : 0
      }
    }, {
      "uid" : "3eec40974c3944e5",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '/Users/sonic/Project/Python/Pytest/logs/2020-04-09.log'",
      "time" : {
        "start" : 1586446302717,
        "stop" : 1586446302717,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "d6001259fa17c304.json",
  "parameterValues" : [ "{'id': 'asc-0003', 'module': 'flask', 'url': 'http://127.0.0.1:8888/login?name=yuhang&pw=999', 'isRun': 'RUN', 'method': 'GET', 'parameter': '', 'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'result': '', 'message': ''}" ]
}